### ISSUE TITLE
Site 500 errors following installation

### ISSUE THREAD

**Issue by jcdm** [Jako/SwitchTemplate#21]
I installed SwitchTemplate  in MODX 3.0.1 and trying to load the CMP or visiting a page on the website with the plugin enabled leads to a 500 error.

The PHP error log gives the following (with paths switched out)
```[16-Aug-2022 14:34:30 Australia/Adelaide] PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /path/to/core/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /path/to/core/components/switchtemplate/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /path/to/core/components/switchtemplate/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /path/to/core/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): GuzzleHttp\Client->__construct()
#3 /path/to/core/vendor/aws/aws-sdk-php/src/functions.php(279): Aws\Handler\GuzzleV6\GuzzleHandler->__construct()
#4 /path/to/core/vendor/aws/aws-sdk-php/src/ClientResolver.php(776): Aws\default_http_handler()
#5 /path/to/core/vendor/aws/aws-sdk-php/src/ClientResolver.php(324): Aws\ClientResolver::_default_handler(Array)
#6 /path/to/core/vendor/aws/aws-sdk-php/src/AwsClient.php(199): Aws\ClientResolver->resolve(A in /path/to/core/vendor/guzzlehttp/guzzle/src/functions.php on line 61```

Server environment is Valet+ running on MacOS - can provide more details if helpful.

**Comment by jcdm** [comment]
MarkH suggested installing the Guzzle7 package which I did and this seems to have resolved the issue.

**Comment by Jako** [comment]
Please check this version: https://github.com/Jako/SwitchTemplate/raw/2.0/_packages/switchtemplate-2.0.0-pl.transport.zip
